In [1]:
import numpy as np
n1 = np.array([1,2,3,4,5])
n1
type(n1)
n2 = np.array([[1,2,3,4,5],[10,20,30,40,50]])    # Inner lists must have same number of elements
n2
n3 = np.zeros((5,4))
n3
n4 = np.full([3,4],-1)
n4
n5 = np.arange(20,10,-2)
n5
n6 = np.random.randint(10,100,10)
n6
n2.shape = (5,2)
n2           

array([[ 1,  2],
       [ 3,  4],
       [ 5, 10],
       [20, 30],
       [40, 50]])

In [ ]:
import ast
arr = ast.literal_eval(input())

In [2]:
n1 = np.array([1,2,3,4])
n2 = np.array([10,20,30,40])
print(np.vstack([n1,n2]))
print(np.hstack((n1,n2)))
np.column_stack((n1,n2))
#np.vstack((n1,n2)).transpose()

[[ 1  2  3  4]
 [10 20 30 40]]
[ 1  2  3  4 10 20 30 40]


array([[ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40]])

In [3]:
n1 = np.array([1,2,3,4,5,6])
n2 = np.array([5,6,7,8,9,10,11,12,13,1])
np.intersect1d(n1,n2)
np.setdiff1d(n2,n1)

array([ 7,  8,  9, 10, 11, 12, 13])

In [4]:
n3 = np.array([10,20])
n4 = np.array([30,40])
np.sum([n3,n4], axis=0)

array([40, 60])

In [5]:
n5 = np.array([10,20,30,40])
n5 += 5
n5 *= 5
n5 -= 5
n5 = n5//5
n5
n6 = np.array([5,10,15,20,25,30])
np.mean(n6)
np.std(n6)
np.median(n6)

17.5

In [6]:
n7 = np.array([[1,2,3,4],[10,20,40,50]])
np.mean(n7)

16.25

In [7]:
n8 = np.array([1,2,3,4,5,6])
np.save('my_numpy',n8)
np.load('my_numpy.npy')

array([1, 2, 3, 4, 5, 6])

Sep 11

In [8]:
list1 = [1,2,3,4,5]
arr1 = np.array(list1)
arr2 = arr1+1
arr2

array([2, 3, 4, 5, 6])

In [9]:
arr3 = np.arange(100,50,-3)
arr3

array([100,  97,  94,  91,  88,  85,  82,  79,  76,  73,  70,  67,  64,
        61,  58,  55,  52])

Executions are fast in numpy array compared to lists

In [10]:
import time
a = time.time()
arr3 = arr3**2
b = time.time()
b-a

0.0

In [11]:
# Random gives uniform distribution output from half open interval [0,1)
n1 = np.random.random(10)
n1.round(3)

array([0.393, 0.582, 0.067, 0.481, 0.345, 0.592, 0.912, 0.   , 0.333,
       0.025])

In [12]:
n6 = np.random.randint(50,100,10).reshape(5,2)
n6

array([[64, 73],
       [60, 59],
       [69, 59],
       [51, 99],
       [67, 69]])

In [13]:
n2 = np.zeros((10,3))
n2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
n3 = np.ones((10,5))
n3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
n4 = np.empty((3,4),dtype='int')
n4

array([[         0, 1080264704,          0, 1078730752],
       [         0, 1075380224,          0, 1075380224],
       [         0, 1078730752,          0, 1080264704]])

In [16]:
n5 = np.full((2,5),10)
n5

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [17]:
Identity_Matrix = np.identity(3)
Identity_Matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
n7 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(n7.size)
print(n7.shape)
print(n7.ndim)
n7.reshape(1,10)

10
(2, 5)
2


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [19]:
n7.reshape(2,5)
n7[0,0] = 2
n7

array([[ 2,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [20]:
n7[1:,3:]

array([[ 9, 10]])

In [21]:
n9 = np.arange(9)
print(np.split(n9,3))
print(np.array_split(n9,2))

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8])]


In [22]:
n10 = np.arange(10).reshape(2,5)
for i in np.nditer(n10):
    print(i+2)

2
3
4
5
6
7
8
9
10
11


In [1]:
n10 = np.arange(10).reshape(2,5)
for i in n10:
    for j in i:
        print(j, end=' ')

0 1 2 3 4 5 6 7 8 9 

In [40]:
# Print Odd rows and Even columns
n11 = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
print('Printing Input Array')
print(n11)
print()
print('Printing array of odd rows and even columns')
print(n11[0:n11.shape[0]:2,1:n11.shape[1]:2])

Printing Input Array
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]

Printing array of odd rows and even columns
[[ 6 12]
 [30 36]
 [54 60]]
